In [1]:
import numpy as np


In [2]:
data = np.random.randint(0,10,10)

In [3]:
data

array([8, 7, 8, 7, 8, 1, 9, 1, 3, 1], dtype=int32)

In [4]:
np.quantile(data,0.5)

np.float64(7.0)

In [5]:
np.median(data)

np.float64(7.0)

In [6]:
np.quantile(data,0.75)

np.float64(8.0)

In [8]:
np.quantile(data,0.25)

np.float64(1.5)

In [10]:
data=np.random.randint(0,10,(3,3))

In [11]:
data

array([[6, 7, 7],
       [4, 6, 6],
       [7, 8, 9]], dtype=int32)

In [12]:
data.T

array([[6, 4, 7],
       [7, 6, 8],
       [7, 6, 9]], dtype=int32)

In [13]:
np.corrcoef(data)

array([[1.       , 1.       , 0.8660254],
       [1.       , 1.       , 0.8660254],
       [0.8660254, 0.8660254, 1.       ]])