In [11]:
import numpy as np
data=np.random.randint(0,100,(5,5))
data

array([[82, 25, 71, 80, 69],
       [30,  8, 76, 48, 85],
       [17, 94, 20, 62, 90],
       [39, 77, 98, 72, 21],
       [49, 65,  7, 60, 85]], dtype=int32)

In [2]:
type(np.array([1,2,3]))

numpy.ndarray

In [7]:
data[0,0]

np.int32(85)

In [8]:
data

array([[85, 80,  2, 62, 46],
       [93, 61, 17, 38,  2],
       [19,  8, 25, 43, 98],
       [51, 68, 77, 44, 70],
       [ 3, 52, 14, 92, 32]], dtype=int32)

In [17]:
print(data)
print(" ")
print(data[-3:-1,-3:-1])

[[82 25 71 80 69]
 [30  8 76 48 85]
 [17 94 20 62 90]
 [39 77 98 72 21]
 [49 65  7 60 85]]
 
[[20 62]
 [98 72]]


In [18]:
print(data)
print(data[-2:-1,-2:-1])

[[82 25 71 80 69]
 [30  8 76 48 85]
 [17 94 20 62 90]
 [39 77 98 72 21]
 [49 65  7 60 85]]
[[72]]


In [21]:
x=[1,2,3]
print(type(x))
y=np.array([1,2,3])
print(type(y))


<class 'list'>
<class 'numpy.ndarray'>


In [22]:
x/2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [23]:
y/2

array([0.5, 1. , 1.5])

In [24]:
x=[1,2,3,6.0]
y=np.array([1,2,3,6.0])

In [25]:
x

[1, 2, 3, 6.0]

In [26]:
y

array([1., 2., 3., 6.])

In [28]:
x=[1,2,3,6.0,"data"]
y=np.array([1,2,3,6.0 ,"data"])

In [29]:
x

[1, 2, 3, 6.0, 'data']

In [30]:
y

array(['1', '2', '3', '6.0', 'data'], dtype='<U32')

In [31]:
###Random family functions

In [33]:
np.random.randint(0,100,(5,10))

array([[11, 97, 69,  5, 48, 86,  8, 76, 73, 23],
       [72, 97, 17, 57, 78, 87, 75, 42, 86, 88],
       [84, 81, 26, 96, 61, 26, 63, 98, 60, 86],
       [ 6, 19, 17, 86, 87, 86, 45,  2, 47, 32],
       [59, 97, 99, 15, 49,  1, 73, 50, 20, 42]], dtype=int32)

In [35]:
np.random.rand(3,3)

array([[0.196496  , 0.0994739 , 0.68344157],
       [0.5230426 , 0.32821495, 0.93716854],
       [0.5491861 , 0.48991005, 0.57469471]])

In [37]:
data = np.array([1,2,3,4])
(data-data.min())/(data.max()-data.min())

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [38]:
(data-data.min())/(data.max()-data.min())

array([0.        , 0.33333333, 0.66666667, 1.        ])