In [1]:
import numpy as np
data = np.random.randint(0,10,(3,3))
data 

array([[7, 2, 8],
       [6, 0, 2],
       [4, 0, 8]], dtype=int32)

In [2]:
np.random.randn(3,3).mean()

np.float64(0.16546847518389485)

In [5]:
np.random.randn(30,30).std()

np.float64(0.9867976355667059)

In [7]:
np.std(data)

np.float64(3.0711722135745005)

In [8]:
np.mean(data)

np.float64(4.111111111111111)

In [9]:
np.median(data)

np.float64(4.0)

In [10]:
np.var(data)

np.float64(9.432098765432096)

In [11]:
data = np.random.randint(0,100,10)
data

array([93, 70, 91, 90, 94,  5, 31, 29, 42, 70], dtype=int32)

In [12]:
range = data.max()-data.min()
range

np.int32(89)

In [13]:
import numpy  as np
data = np.random.randint(0,5,(3,3))
data

array([[3, 0, 2],
       [2, 1, 0],
       [0, 4, 3]], dtype=int32)

In [16]:
data.sum(axis=1)

array([5, 3, 7])

In [17]:
data.sum(axis=0)

array([5, 5, 5])

In [22]:
np.random.randint(0,10,(3,3))

array([[6, 7, 3],
       [3, 8, 9],
       [6, 4, 1]], dtype=int32)

In [23]:
data.max(axis=0)

array([3, 4, 3], dtype=int32)

In [25]:
data.min(axis=1)

array([0, 0, 0], dtype=int32)

In [26]:
data

array([[3, 0, 2],
       [2, 1, 0],
       [0, 4, 3]], dtype=int32)

In [28]:
data[0:2,0:2].max()

np.int32(3)

In [30]:
data = np.random.randint(0,10,10)
data 

array([1, 0, 6, 5, 7, 0, 5, 7, 9, 6], dtype=int32)

In [31]:
data.min()

np.int32(0)

In [32]:
data.argmin()

np.int64(1)

In [34]:
data=np.random.randint(0,100,(3,3))
data 

array([[69, 21,  5],
       [41, 86, 44],
       [93, 81, 73]], dtype=int32)

In [35]:
data.argmin(axis=1)

array([2, 0, 2])

In [36]:
import numpy as np

# Manually created array: [Store ID, Sales, Customers, Inventory, Returns]
retail_data = np.array([
    [1, 25000, 300, 1200, 10],
    [2, 32000, 450, 1500, 15],
    [3, 28000, 380, 1100, 8],
    [4, 41000, 500, 1600, 20],
    [5, 35000, 420, 1400, 12],
    [6, 27000, 360, 1300, 9],
    [7, 39000, 480, 1700, 18],
    [8, 30000, 400, 1250, 14],
    [9, 45000, 550, 1800, 25],
    [10, 33000, 410, 1450, 11]
])

print(retail_data)

[[    1 25000   300  1200    10]
 [    2 32000   450  1500    15]
 [    3 28000   380  1100     8]
 [    4 41000   500  1600    20]
 [    5 35000   420  1400    12]
 [    6 27000   360  1300     9]
 [    7 39000   480  1700    18]
 [    8 30000   400  1250    14]
 [    9 45000   550  1800    25]
 [   10 33000   410  1450    11]]


In [39]:
retail_data[:,1].sum()

np.int64(335000)

In [40]:
retail_data[:,3].argmax()+1

np.int64(9)

In [47]:
(retail_data[:,1]/retail_data[:,2])

array([83.33333333, 71.11111111, 73.68421053, 82.        , 83.33333333,
       75.        , 81.25      , 75.        , 81.81818182, 80.48780488])

In [45]:
(retail_data[:,1]/retail_data[:,2]).argmax()+1

np.int64(1)

In [46]:
retail_data

array([[    1, 25000,   300,  1200,    10],
       [    2, 32000,   450,  1500,    15],
       [    3, 28000,   380,  1100,     8],
       [    4, 41000,   500,  1600,    20],
       [    5, 35000,   420,  1400,    12],
       [    6, 27000,   360,  1300,     9],
       [    7, 39000,   480,  1700,    18],
       [    8, 30000,   400,  1250,    14],
       [    9, 45000,   550,  1800,    25],
       [   10, 33000,   410,  1450,    11]])

In [50]:
data=np.random.randint(0,10,3)
x=20

In [51]:
data+x

array([23, 25, 22], dtype=int32)

In [52]:
data

array([3, 5, 2], dtype=int32)

In [53]:
x=np.random.randint(0,10,(3,1))
y=np.random.randint(0,10,(1,3))
x+y

array([[13,  9,  9],
       [11,  7,  7],
       [17, 13, 13]], dtype=int32)

In [54]:
x

array([[5],
       [3],
       [9]], dtype=int32)

In [55]:
y

array([[8, 4, 4]], dtype=int32)

In [56]:
x=np.random.randint(0,10,(3,3))
y=np.random.randint(0,10,(1,3))
x+y

array([[ 7, 13, 14],
       [14,  9, 15],
       [12,  6, 17]], dtype=int32)

In [57]:
x

array([[1, 7, 5],
       [8, 3, 6],
       [6, 0, 8]], dtype=int32)

In [58]:
y

array([[6, 6, 9]], dtype=int32)