In [1]:
import numpy as np
data = np.random.randint(0,10,(3,3))
data

array([[6, 3, 6],
       [4, 4, 2],
       [9, 4, 1]], dtype=int32)

In [2]:
### array creations functions

In [3]:
np.array([1,2,3])

array([1, 2, 3])

In [4]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
np.ones(3)

array([1., 1., 1.])

In [7]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [10]:
### Mathematical Functions

In [11]:
data = np.random.randint(0,100,10)
data

array([62, 60, 94, 55,  5, 61, 44, 97, 41, 50], dtype=int32)

In [12]:
print(np.sin(data))
print(np.cos(data))
print(np.tan(data))

[-0.7391807  -0.30481062 -0.24525199 -0.99975517 -0.95892427 -0.96611777
  0.01770193  0.37960774 -0.15862267 -0.26237485]
[ 0.67350716 -0.95241298  0.96945937  0.02212676  0.28366219 -0.25810164
  0.99984331 -0.92514754 -0.98733928  0.96496603]
[-1.09750978e+00  3.20040389e-01 -2.52978097e-01 -4.51830879e+01
 -3.38051501e+00  3.74316794e+00  1.77046993e-02 -4.10321299e-01
  1.60656699e-01 -2.71900612e-01]


In [13]:
np.arccos(data)

C:\Users\admin\AppData\Local\Temp\ipykernel_7632\4017286375.py:1: RuntimeWarning: invalid value encountered in arccos
  np.arccos(data)


array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [14]:
np.arctan(data)

array([1.55466869, 1.5541312 , 1.56015843, 1.55261651, 1.37340077,
       1.55440435, 1.54807297, 1.56048741, 1.54641092, 1.55079899])

In [15]:
np.arcsin(np.array([1,0.5]))

array([1.57079633, 0.52359878])

In [16]:
data

array([62, 60, 94, 55,  5, 61, 44, 97, 41, 50], dtype=int32)

In [17]:
np.log(data)

array([4.12713439, 4.09434456, 4.54329478, 4.00733319, 1.60943791,
       4.11087386, 3.78418963, 4.57471098, 3.71357207, 3.91202301])

In [18]:
np.log10(data)

array([1.79239169, 1.77815125, 1.97312785, 1.74036269, 0.69897   ,
       1.78532984, 1.64345268, 1.98677173, 1.61278386, 1.69897   ])

In [19]:
np.log2(data)

array([5.95419631, 5.9068906 , 6.55458885, 5.78135971, 2.32192809,
       5.93073734, 5.45943162, 6.59991284, 5.357552  , 5.64385619])

In [20]:
np.e

2.718281828459045

In [21]:
import math
np.log(math.pow(2.718281828459045,0.2867))

np.float64(0.2867)

In [22]:
data1 = np.random.randint(0,10,(3,3))
data2 = np.random.randint(0,10,(3,3))
data1

array([[7, 6, 7],
       [7, 7, 5],
       [0, 4, 9]], dtype=int32)

In [23]:
data2

array([[7, 9, 8],
       [3, 4, 1],
       [2, 3, 0]], dtype=int32)

In [24]:
np.add(data1,data2)

array([[14, 15, 15],
       [10, 11,  6],
       [ 2,  7,  9]], dtype=int32)

In [25]:
np.subtract(data1,data2)

array([[ 0, -3, -1],
       [ 4,  3,  4],
       [-2,  1,  9]], dtype=int32)

In [26]:
np.multiply(data1,data2)

array([[49, 54, 56],
       [21, 28,  5],
       [ 0, 12,  0]], dtype=int32)

In [27]:
np.divide(data1,data2)

C:\Users\admin\AppData\Local\Temp\ipykernel_7632\18017515.py:1: RuntimeWarning: divide by zero encountered in divide
  np.divide(data1,data2)


array([[1.        , 0.66666667, 0.875     ],
       [2.33333333, 1.75      , 5.        ],
       [0.        , 1.33333333,        inf]])

In [28]:
data1

array([[7, 6, 7],
       [7, 7, 5],
       [0, 4, 9]], dtype=int32)

In [29]:
data2

array([[7, 9, 8],
       [3, 4, 1],
       [2, 3, 0]], dtype=int32)

In [30]:
np.floor_divide(data1,data2)

C:\Users\admin\AppData\Local\Temp\ipykernel_7632\583036681.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.floor_divide(data1,data2)


array([[1, 0, 0],
       [2, 1, 5],
       [0, 1, 0]], dtype=int32)

In [31]:
data = np.random.randint(0,10,10)/5
print(data)
np.ceil(data)

[0.2 0.6 1.2 1.4 0.8 0.8 1.6 1.8 1.8 0.6]


array([1., 1., 2., 2., 1., 1., 2., 2., 2., 1.])

In [32]:
np.floor(data)

array([0., 0., 1., 1., 0., 0., 1., 1., 1., 0.])

In [33]:
import numpy as np
data = np.random.randint(0,10,10)
data


array([1, 9, 0, 0, 1, 8, 2, 4, 2, 9], dtype=int32)

In [34]:
data[data>5]

array([9, 8, 9], dtype=int32)

In [35]:
marks=np.random.randint(10,100,20)
marks

array([66, 82, 67, 85, 62, 32, 48, 15, 90, 51, 15, 34, 89, 73, 26, 85, 83,
       67, 20, 39], dtype=int32)

In [36]:
marks[marks<=50]

array([32, 48, 15, 15, 34, 26, 20, 39], dtype=int32)

In [37]:
marks[marks<=np.mean(marks)]

array([32, 48, 15, 51, 15, 34, 26, 20, 39], dtype=int32)

In [ ]:
### array manipulation

In [40]:
data = np.random.randint(0,10,(3,3))

In [41]:
data

array([[4, 0, 5],
       [1, 8, 3],
       [4, 7, 8]], dtype=int32)

In [42]:
data.ravel()

array([4, 0, 5, 1, 8, 3, 4, 7, 8], dtype=int32)

In [43]:
data.T

array([[4, 1, 4],
       [0, 8, 7],
       [5, 3, 8]], dtype=int32)

In [3]:
import numpy as np
data = np.random.randint(0,10,20)
data.reshape(2,10)

array([[0, 7, 4, 7, 2, 4, 9, 8, 4, 7],
       [7, 3, 3, 4, 3, 1, 1, 1, 6, 6]], dtype=int32)

In [4]:
data1 = np.random.randint(0,10,(4,3))
data2 = np.random.randint(0,10,(4,3))

In [5]:
data1

array([[1, 6, 5],
       [3, 7, 2],
       [4, 6, 1],
       [7, 1, 9]], dtype=int32)

In [6]:
data2

array([[8, 7, 3],
       [5, 1, 8],
       [2, 3, 1],
       [2, 9, 0]], dtype=int32)

In [7]:
data1.T

array([[1, 3, 4, 7],
       [6, 7, 6, 1],
       [5, 2, 1, 9]], dtype=int32)

In [8]:
data2.T

array([[8, 5, 2, 2],
       [7, 1, 3, 9],
       [3, 8, 1, 0]], dtype=int32)

In [10]:
np.hstack([data1,data2])

array([[1, 6, 5, 8, 7, 3],
       [3, 7, 2, 5, 1, 8],
       [4, 6, 1, 2, 3, 1],
       [7, 1, 9, 2, 9, 0]], dtype=int32)

In [11]:
np.vstack([data1,data2])

array([[1, 6, 5],
       [3, 7, 2],
       [4, 6, 1],
       [7, 1, 9],
       [8, 7, 3],
       [5, 1, 8],
       [2, 3, 1],
       [2, 9, 0]], dtype=int32)

In [17]:
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])

In [29]:

split_data = np.vsplit(matrix, 2)

print(split_data)


[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])]
