In [1]:
import numpy as np
data = np.random.randint(0,10,(3,3))
data

array([[0, 0, 6],
       [1, 6, 1],
       [4, 4, 8]], dtype=int32)

In [2]:
### array creations functions

In [3]:
np.array([1,2,3])

array([1, 2, 3])

In [4]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
np.ones(3)

array([1., 1., 1.])

In [7]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [10]:
### Mathematical Functions

In [11]:
data = np.random.randint(0,100,10)
data

array([ 2, 83, 27, 28, 10, 30, 20, 58, 89, 55], dtype=int32)

In [12]:
print(np.sin(data))
print(np.cos(data))
print(np.tan(data))

[ 0.90929743  0.96836446  0.95637593  0.27090579 -0.54402111 -0.98803162
  0.91294525  0.99287265  0.86006941 -0.99975517]
[-0.41614684  0.24954012 -0.29213881 -0.96260587 -0.83907153  0.15425145
  0.40808206  0.11918014  0.51017704  0.02212676]
[ -2.18503986   3.88059631  -3.2737038   -0.2814296    0.64836083
  -6.4053312    2.23716094   8.33085685   1.68582537 -45.18308791]


In [13]:
np.arccos(data)

C:\Users\admin\AppData\Local\Temp\ipykernel_15940\4017286375.py:1: RuntimeWarning: invalid value encountered in arccos
  np.arccos(data)


array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [14]:
np.arctan(data)

array([1.10714872, 1.55874872, 1.53377621, 1.53509721, 1.47112767,
       1.53747533, 1.52083793, 1.55355666, 1.55956084, 1.55261651])

In [15]:
np.arcsin(np.array([1,0.5]))

array([1.57079633, 0.52359878])

In [16]:
data

array([ 2, 83, 27, 28, 10, 30, 20, 58, 89, 55], dtype=int32)

In [17]:
np.log(data)

array([0.69314718, 4.41884061, 3.29583687, 3.33220451, 2.30258509,
       3.40119738, 2.99573227, 4.06044301, 4.48863637, 4.00733319])

In [18]:
np.log10(data)

array([0.30103   , 1.91907809, 1.43136376, 1.44715803, 1.        ,
       1.47712125, 1.30103   , 1.76342799, 1.94939001, 1.74036269])

In [19]:
np.log2(data)

array([1.        , 6.37503943, 4.7548875 , 4.80735492, 3.32192809,
       4.9068906 , 4.32192809, 5.857981  , 6.47573343, 5.78135971])

In [20]:
np.e

2.718281828459045

In [21]:
import math
np.log(math.pow(2.718281828459045,0.2867))

np.float64(0.2867)

In [22]:
data1 = np.random.randint(0,10,(3,3))
data2 = np.random.randint(0,10,(3,3))
data1

array([[3, 5, 0],
       [6, 8, 6],
       [8, 7, 6]], dtype=int32)

In [23]:
data2

array([[5, 9, 5],
       [6, 2, 4],
       [9, 2, 9]], dtype=int32)

In [24]:
np.add(data1,data2)

array([[ 8, 14,  5],
       [12, 10, 10],
       [17,  9, 15]], dtype=int32)

In [25]:
np.subtract(data1,data2)

array([[-2, -4, -5],
       [ 0,  6,  2],
       [-1,  5, -3]], dtype=int32)

In [26]:
np.multiply(data1,data2)

array([[15, 45,  0],
       [36, 16, 24],
       [72, 14, 54]], dtype=int32)

In [27]:
np.divide(data1,data2)

array([[0.6       , 0.55555556, 0.        ],
       [1.        , 4.        , 1.5       ],
       [0.88888889, 3.5       , 0.66666667]])

In [28]:
data1

array([[3, 5, 0],
       [6, 8, 6],
       [8, 7, 6]], dtype=int32)

In [29]:
data2

array([[5, 9, 5],
       [6, 2, 4],
       [9, 2, 9]], dtype=int32)

In [30]:
np.floor_divide(data1,data2)

array([[0, 0, 0],
       [1, 4, 1],
       [0, 3, 0]], dtype=int32)

In [31]:
data = np.random.randint(0,10,10)/5
print(data)
np.ceil(data)

[1.6 0.4 0.8 1.4 1.6 0.4 0.8 0.2 0.6 1. ]


array([2., 1., 1., 2., 2., 1., 1., 1., 1., 1.])

In [32]:
np.floor(data)

array([1., 0., 0., 1., 1., 0., 0., 0., 0., 1.])

In [33]:
import numpy as np
data = np.random.randint(0,10,10)
data


array([7, 9, 5, 2, 5, 1, 0, 9, 0, 3], dtype=int32)

In [34]:
data[data>5]

array([7, 9, 9], dtype=int32)

In [35]:
marks=np.random.randint(10,100,20)
marks

array([35, 57, 71, 86, 52, 88, 32, 32, 99, 22, 85, 34, 83, 25, 18, 57, 26,
       27, 26, 77], dtype=int32)

In [36]:
marks[marks<=50]

array([35, 32, 32, 22, 34, 25, 18, 26, 27, 26], dtype=int32)